version: '3'

services:
    node:
        build:
            context: ./node
        image: node
        tty: true
    ca:
        build:
            context: ./ca
        image: ca
        tty: true
        networks:
            default:
                ipv4_address: 192.168.0.10
#    test:
#        build:
#            context: ./test
#        image: test
#        tty: true
#        stdin_open: true
#        entrypoint: /bin/sh
#        networks:
#            default:
#                ipv4_address: 192.168.0.11

networks:
    default:
        ipam:
            driver: default
            config:
                - subnet: "192.168.0.0/24"
